import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js';
import { getFirestore, doc, getDoc, setDoc, collection, addDoc, getDocs, query, orderBy, limit, onSnapshot, runTransaction, serverTimestamp } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js';

const config = window.MELATION_FIREBASE_CONFIG || {};
const firebaseConfigured = Boolean(config.apiKey && config.projectId && config.appId);
const FIREBASE_ROOT = 'melationSound';
const FIREBASE_ROOT_ID = 'main';
const ACCOUNT_SESSION_KEY = 'melationSoundAccount';
const LOCAL_KEY = 'melationCommunityDemo';
const catalog = [
  { id:'01', title:'A Dreams A Mystery', artist:'Osama, MT', art:'album-cover.png', href:'song.html?track=01' },
  { id:'02', title:'Nightmare Fuel', artist:'Osama, MT and Adam', art:'Nightmare Fuel.png', href:'song.html?track=02' },
  { id:'11', title:"Nawaf's Stole Pain", artist:'Bassam', art:"Nawaf's Stole Pain.png", href:'song.html?track=11' },
  { id:'10-20', title:'10:20', artist:'MT', art:'1020.png', href:'song.html?track=10-20', private:true }
];
const catalogById = Object.fromEntries(catalog.map(item => [item.id, item]));
let db = null;
let root = null;
let accounts = null;
let currentUser = null;

function normalizeUsername(value = '') { return String(value).trim().toLowerCase().replace(/\s+/g, '-'); }
function songInfo(id) { return catalogById[id] || { id, title:id, artist:'Melation Sound', art:'melation-sound.png', href:'song.html?track=' + encodeURIComponent(id) }; }
function escapeHtml(value) { return String(value == null ? '' : value).replace(/[&<>"']/g, character => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character])); }
function formatDuration(seconds) { seconds = Math.max(0, Math.round(Number(seconds) || 0)); const hours = Math.floor(seconds / 3600); const minutes = Math.floor((seconds % 3600) / 60); return hours ? hours + 'h ' + minutes + 'm' : minutes + 'm ' + String(seconds % 60).padStart(2, '0') + 's'; }
function setText(id, value) { const element = document.getElementById(id); if (element) element.textContent = value; }
function setSetup(message) { const element = document.getElementById('communitySetup'); if (element) { element.hidden = false; element.textContent = message; } const profileState = document.getElementById('profileState'); if (profileState) profileState.textContent = message; }
function readLocal() { try { return JSON.parse(localStorage.getItem(LOCAL_KEY) || 'null') || {uid:'local-listener', username:'local-listener', displayName:'Local listener', totalSeconds:0, uniqueSongs:0, plays:0, songs:{}, reactions:{}, comments:{}}; } catch (error) { return {uid:'local-listener', username:'local-listener', displayName:'Local listener', totalSeconds:0, uniqueSongs:0, plays:0, songs:{}, reactions:{}, comments:{}}; } }
function writeLocal(value) { try { localStorage.setItem(LOCAL_KEY, JSON.stringify(value)); } catch (error) {} }
function readSession() { try { return JSON.parse(sessionStorage.getItem(ACCOUNT_SESSION_KEY) || 'null'); } catch (error) { return null; } }
function writeSession(value) { try { if (value) sessionStorage.setItem(ACCOUNT_SESSION_KEY, JSON.stringify(value)); else sessionStorage.removeItem(ACCOUNT_SESSION_KEY); } catch (error) {} }
async function hashPin(usernameKey, pin) { const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(usernameKey + ':' + pin)); return Array.from(new Uint8Array(digest)).map(byte => byte.toString(16).padStart(2, '0')).join(''); }
function getCredentials() { const username = normalizeUsername(document.getElementById('communityDisplayName')?.value); const pin = document.getElementById('communityPassword')?.value || ''; if (!/^[a-z0-9_-]{2,20}$/.test(username)) throw new Error('Username must be 2–20 characters using letters, numbers, hyphens, or underscores.'); if (!/^\d{6}$/.test(pin)) throw new Error('PIN must be exactly 6 digits.'); return {username, pin}; }

function setSongCounts(stats) { setText('songViewCount', stats.views || 0); setText('songLikeCount', (stats.likesBy || []).length || stats.likes || 0); setText('songDislikeCount', (stats.dislikesBy || []).length || stats.dislikes || 0); const like = document.getElementById('songLike'); const dislike = document.getElementById('songDislike'); if (like) { like.classList.toggle('is-active', stats.reaction === 'like'); like.setAttribute('aria-pressed', String(stats.reaction === 'like')); } if (dislike) { dislike.classList.toggle('is-active', stats.reaction === 'dislike'); dislike.setAttribute('aria-pressed', String(stats.reaction === 'dislike')); } }
function renderComments(comments) { const target = document.getElementById('songCommentList'); if (!target) return; target.innerHTML = comments.length ? comments.map(comment => '<article class="song-comment"><div class="song-comment-meta"><strong>' + escapeHtml(comment.author || 'Listener') + '</strong><span>Listener comment</span></div><p>' + escapeHtml(comment.body || comment.text) + '</p></article>').join('') : '<p class="song-comment-empty">No comments yet. Start the conversation.</p>'; }
function localSongStats(id) { const data = readLocal(); const engagement = window.MelationEngagement ? window.MelationEngagement.get(id) : {views:0, likes:0, dislikes:0}; const reaction = data.reactions[id]?.type || engagement.reaction || null; return {views:engagement.views || 0, likes:engagement.likes || 0, dislikes:engagement.dislikes || 0, reaction}; }
function renderLocalComments(id) { const data = readLocal(); renderComments((data.comments?.[id] || []).slice().reverse()); }
function localListenerRows() { const data = readLocal(); return [{uid:data.uid, displayName:data.displayName, totalSeconds:data.totalSeconds || 0, uniqueSongs:data.uniqueSongs || Object.keys(data.songs || {}).length, plays:data.plays || 0}]; }
function renderListenerRows(rows) { const target = document.getElementById('listenerChart'); if (!target) return; target.innerHTML = rows.length ? rows.map((row, index) => '<a class="listener-row" href="profile.html?uid=' + encodeURIComponent(row.uid) + '"><span class="listener-rank">' + String(index + 1).padStart(2, '0') + '</span><span class="listener-copy"><strong>' + escapeHtml(row.displayName || row.username || 'Listener') + '</strong><small>' + (row.uniqueSongs || 0) + ' songs · ' + (row.plays || 0) + ' plays</small></span><span class="listener-value">' + formatDuration(row.totalSeconds) + '<small>listened</small></span></a>').join('') : '<p class="community-empty">No listener profiles yet. Create an account and start playing.</p>'; }
function renderProfileLists(data) { const listened = Object.values(data.songs || {}).sort((a,b) => (b.seconds || 0) - (a.seconds || 0)); const reactions = Object.values(data.reactions || {}); const render = (targetId, items, value) => { const target = document.getElementById(targetId); if (!target) return; target.innerHTML = items.length ? items.map(item => '<li class="profile-song"><img src="' + escapeHtml(item.art || songInfo(item.songId).art) + '" alt=""><span class="profile-song-copy"><strong>' + escapeHtml(item.title || songInfo(item.songId).title) + '</strong><small>' + escapeHtml(item.artist || songInfo(item.songId).artist) + '</small></span><span class="profile-song-value">' + escapeHtml(value(item)) + '</span></li>').join('') : '<li class="community-empty">Nothing here yet.</li>'; }; render('listenedList', listened, item => formatDuration(item.seconds) + ' · ' + (item.plays || 0) + ' plays'); render('likedList', reactions.filter(item => item.type === 'like'), () => 'Liked'); render('dislikedList', reactions.filter(item => item.type === 'dislike'), () => 'Disliked'); setText('profileName', data.displayName || data.username || 'Listener'); setText('profileHandle', '@' + (data.username || String(data.uid || 'listener').slice(0, 12))); const stats = document.getElementById('profileStats'); if (stats) stats.innerHTML = '<div class="profile-stat"><strong>' + formatDuration(data.totalSeconds) + '</strong><span>listened</span></div><div class="profile-stat"><strong>' + (data.uniqueSongs || listened.length) + '</strong><span>songs</span></div><div class="profile-stat"><strong>' + (data.plays || listened.reduce((total, item) => total + (item.plays || 0), 0)) + '</strong><span>plays</span></div>'; }

async function accountSnapshot(usernameKey) { const snapshot = await getDoc(doc(accounts, usernameKey)); return snapshot.exists() ? {...snapshot.data(), uid:usernameKey, usernameKey} : null; }
async function loadAccount(usernameKey) { const data = await accountSnapshot(usernameKey); if (!data) return null; data.songs = {}; data.reactions = {}; const accountRef = doc(accounts, usernameKey); const listens = await getDocs(query(collection(accountRef, 'listens'), orderBy('seconds', 'desc'), limit(50))); const reactions = await getDocs(collection(accountRef, 'reactions')); listens.forEach(item => { data.songs[item.id] = {...item.data(), songId:item.id, ...songInfo(item.id)}; }); reactions.forEach(item => { data.reactions[item.id] = {...item.data(), songId:item.id, ...songInfo(item.id)}; }); return data; }
async function login(username, pin, createIfMissing = true) { const usernameKey = normalizeUsername(username); const reference = doc(accounts, usernameKey); const existing = await getDoc(reference); const pinHash = await hashPin(usernameKey, pin); if (existing.exists()) { const account = existing.data(); if (account.pinHash !== pinHash) throw new Error('That PIN does not match this username.'); currentUser = {uid:usernameKey, username:account.username || username.trim(), usernameKey, displayName:account.displayName || account.username || username.trim()}; } else if (createIfMissing) { const account = {username:username.trim(), usernameKey, displayName:username.trim(), pinHash, totalSeconds:0, uniqueSongs:0, plays:0, createdAtMs:Date.now()}; await setDoc(reference, account); currentUser = {uid:usernameKey, username:account.username, usernameKey, displayName:account.displayName}; } else throw new Error('Account not found.'); writeSession(currentUser); updateAccountUi(); return currentUser; }
function logout() { currentUser = null; writeSession(null); updateAccountUi(); }
function updateAccountUi() { const authPanel = document.getElementById('communityAuth'); const userPanel = document.getElementById('communityUser'); if (!authPanel || !userPanel) return; if (currentUser) { authPanel.style.display = 'none'; userPanel.classList.add('is-visible'); setText('communityUserName', currentUser.displayName); setText('communityUserEmail', '@' + currentUser.username); const link = document.getElementById('communityProfileLink'); if (link) link.href = 'profile.html?uid=' + encodeURIComponent(currentUser.usernameKey); } else { authPanel.style.display = ''; userPanel.classList.remove('is-visible'); } }
function renderLocalAccount() { const data = readLocal(); setText('communityMode', 'Demo mode'); const authPanel = document.getElementById('communityAuth'); const userPanel = document.getElementById('communityUser'); if (authPanel && userPanel) { authPanel.style.display = 'none'; userPanel.classList.add('is-visible'); setText('communityUserName', data.displayName); setText('communityUserEmail', 'Demo mode · saved on this device'); const link = document.getElementById('communityProfileLink'); if (link) link.href = 'profile.html?uid=local-listener'; } }
function openAuthPrompt() { const input = document.getElementById('communityDisplayName'); if (input) { input.focus(); input.scrollIntoView({behavior:'smooth', block:'center'}); } setText('songCommentNote', 'Sign in on the Account page to react or comment.'); }

async function recordView(id) { if (window.MelationEngagement) window.MelationEngagement.recordView(id); if (!db) return; let viewed = {}; try { viewed = JSON.parse(sessionStorage.getItem('melationFirebaseViewedSongs') || '{}'); } catch (error) {} if (viewed[id]) return; viewed[id] = true; try { sessionStorage.setItem('melationFirebaseViewedSongs', JSON.stringify(viewed)); } catch (error) {} const reference = doc(root, 'songs', id); runTransaction(db, async transaction => { const snapshot = await transaction.get(reference); const data = snapshot.exists() ? snapshot.data() : {}; transaction.set(reference, {id, title:songInfo(id).title, artist:songInfo(id).artist, art:songInfo(id).art, views:(data.views || 0) + 1, likesBy:data.likesBy || [], dislikesBy:data.dislikesBy || [], updatedAtMs:Date.now()}, {merge:true}); }).catch(() => {}); }
async function recordPlay(id) { const data = readLocal(); data.songs = data.songs || {}; data.songs[id] = data.songs[id] || {...songInfo(id), songId:id, seconds:0, plays:0}; data.songs[id].plays = (data.songs[id].plays || 0) + 1; data.plays = (data.plays || 0) + 1; data.uniqueSongs = Object.keys(data.songs).length; writeLocal(data); if (!db || !currentUser) return; const accountRef = doc(accounts, currentUser.usernameKey); const listenRef = doc(accountRef, 'listens', id); runTransaction(db, async transaction => { const accountSnapshot = await transaction.get(accountRef); const listenSnapshot = await transaction.get(listenRef); const account = accountSnapshot.exists() ? accountSnapshot.data() : {}; const listen = listenSnapshot.exists() ? listenSnapshot.data() : {}; transaction.set(listenRef, {songId:id, title:songInfo(id).title, artist:songInfo(id).artist, art:songInfo(id).art, seconds:listen.seconds || 0, plays:(listen.plays || 0) + 1, updatedAtMs:Date.now()}, {merge:true}); transaction.set(accountRef, {plays:(account.plays || 0) + 1, uniqueSongs:(account.uniqueSongs || 0) + (listenSnapshot.exists() ? 0 : 1), updatedAtMs:Date.now()}, {merge:true}); }).catch(() => {}); }
async function recordListen(id, seconds) { if (!seconds || seconds < 1) return; const data = readLocal(); data.songs = data.songs || {}; data.songs[id] = data.songs[id] || {...songInfo(id), songId:id, seconds:0, plays:0}; data.songs[id].seconds = (data.songs[id].seconds || 0) + seconds; data.totalSeconds = (data.totalSeconds || 0) + seconds; data.uniqueSongs = Object.keys(data.songs).length; writeLocal(data); if (!db || !currentUser) return; const accountRef = doc(accounts, currentUser.usernameKey); const listenRef = doc(accountRef, 'listens', id); runTransaction(db, async transaction => { const accountSnapshot = await transaction.get(accountRef); const listenSnapshot = await transaction.get(listenRef); const account = accountSnapshot.exists() ? accountSnapshot.data() : {}; const listen = listenSnapshot.exists() ? listenSnapshot.data() : {}; transaction.set(listenRef, {songId:id, title:songInfo(id).title, artist:songInfo(id).artist, art:songInfo(id).art, seconds:(listen.seconds || 0) + seconds, plays:listen.plays || 1, updatedAtMs:Date.now()}, {merge:true}); transaction.set(accountRef, {totalSeconds:(account.totalSeconds || 0) + seconds, uniqueSongs:(account.uniqueSongs || 0) + (listenSnapshot.exists() ? 0 : 1), updatedAtMs:Date.now()}, {merge:true}); }).catch(() => {}); }
async function react(id, type) { if (!db || !currentUser) { if (!db) { const data = readLocal(); data.reactions = data.reactions || {}; const old = data.reactions[id]?.type; if (old === type) delete data.reactions[id]; else data.reactions[id] = {songId:id, type, ...songInfo(id)}; writeLocal(data); if (window.MelationEngagement) window.MelationEngagement.react(id, type); const stats = localSongStats(id); setSongCounts({...stats, reaction:old === type ? null : type}); return stats; } openAuthPrompt(); return null; } const songRef = doc(root, 'songs', id); const reactionRef = doc(accounts, currentUser.usernameKey, 'reactions', id); const result = await runTransaction(db, async transaction => { const songSnapshot = await transaction.get(songRef); const reactionSnapshot = await transaction.get(reactionRef); const song = songSnapshot.exists() ? songSnapshot.data() : {}; const likesBy = Array.isArray(song.likesBy) ? song.likesBy.slice() : []; const dislikesBy = Array.isArray(song.dislikesBy) ? song.dislikesBy.slice() : []; const old = reactionSnapshot.exists() ? reactionSnapshot.data().type : null; const remove = old === type; const add = (list, value) => list.includes(value) ? list : list.concat(value); if (type === 'like') { if (remove) { const index = likesBy.indexOf(currentUser.usernameKey); if (index >= 0) likesBy.splice(index, 1); } else { if (old === 'dislike') { const index = dislikesBy.indexOf(currentUser.usernameKey); if (index >= 0) dislikesBy.splice(index, 1); } likesBy.splice(0, likesBy.length, ...add(likesBy, currentUser.usernameKey)); } } else { if (remove) { const index = dislikesBy.indexOf(currentUser.usernameKey); if (index >= 0) dislikesBy.splice(index, 1); } else { if (old === 'like') { const index = likesBy.indexOf(currentUser.usernameKey); if (index >= 0) likesBy.splice(index, 1); } dislikesBy.splice(0, dislikesBy.length, ...add(dislikesBy, currentUser.usernameKey)); } } transaction.set(songRef, {id, title:songInfo(id).title, artist:songInfo(id).artist, art:songInfo(id).art, views:song.views || 0, likesBy, dislikesBy, updatedAtMs:Date.now()}, {merge:true}); if (remove) transaction.delete(reactionRef); else transaction.set(reactionRef, {songId:id, type, title:songInfo(id).title, artist:songInfo(id).artist, art:songInfo(id).art, updatedAtMs:Date.now()}); return {views:song.views || 0, likesBy, dislikesBy, reaction:remove ? null : type}; }); setSongCounts(result); return result; }
async function postComment(id, value) { if (!value) return; if (!db || !currentUser) { if (!db) { const data = readLocal(); data.comments = data.comments || {}; data.comments[id] = data.comments[id] || []; data.comments[id].push({author:data.displayName, body:value, createdAtMs:Date.now()}); writeLocal(data); renderLocalComments(id); return; } openAuthPrompt(); return; } await addDoc(collection(root, 'songComments', id, 'comments'), {author:currentUser.displayName, usernameKey:currentUser.usernameKey, body:value, createdAtMs:Date.now(), createdAt:serverTimestamp()}); }
function renderSongCommunity(id) { const form = document.getElementById('songCommentForm'); const text = document.getElementById('songCommentText'); if (!form || !text) return; form.addEventListener('submit', event => { event.preventDefault(); const value = text.value.trim(); postComment(id, value).then(() => { text.value = ''; }); }); if (!db) { setSongCounts(localSongStats(id)); renderLocalComments(id); setText('songCommentNote', 'Demo mode: saved on this device until Firebase is connected.'); return; } onSnapshot(doc(root, 'songs', id), snapshot => { const data = snapshot.exists() ? snapshot.data() : {}; setSongCounts(data); }); onSnapshot(query(collection(root, 'songComments', id, 'comments'), orderBy('createdAtMs', 'desc'), limit(50)), snapshot => renderComments(snapshot.docs.map(item => item.data())), () => setText('songCommentNote', 'Comments are temporarily unavailable.')); setText('songCommentNote', currentUser ? 'Signed in. Keep it respectful.' : 'Sign in on the Account page to comment.'); }
function renderRemoteListeners() { if (!db || !document.getElementById('listenerChart')) return; onSnapshot(query(accounts, orderBy('totalSeconds', 'desc'), limit(25)), snapshot => renderListenerRows(snapshot.docs.map(item => ({...item.data(), uid:item.id}))), () => setText('listenerChart', 'Listener chart is not available yet.')); }
function renderRemoteProfile(uid) { if (!db || !uid) { setText('profileState', 'Sign in or open a listener profile from the chart.'); return; } loadAccount(normalizeUsername(uid)).then(data => { if (data) { renderProfileLists(data); setText('profileState', 'Shared Firestore profile'); } else setText('profileState', 'This listener profile does not exist yet.'); }).catch(() => setText('profileState', 'Profile data is temporarily unavailable.')); }
function renderRemoteSongCharts() { if (!db || !document.getElementById('viewsChart')) return; onSnapshot(collection(root, 'songs'), snapshot => { const stats = {}; snapshot.forEach(item => { stats[item.id] = item.data(); }); ['views','likes','dislikes'].forEach(metric => { const target = document.getElementById(metric === 'views' ? 'viewsChart' : metric === 'likes' ? 'likesChart' : 'dislikesChart'); if (!target) return; const rows = catalog.slice().sort((a,b) => { const av = metric === 'likes' ? (stats[a.id]?.likesBy || []).length : metric === 'dislikes' ? (stats[a.id]?.dislikesBy || []).length : (stats[a.id]?.views || 0); const bv = metric === 'likes' ? (stats[b.id]?.likesBy || []).length : metric === 'dislikes' ? (stats[b.id]?.dislikesBy || []).length : (stats[b.id]?.views || 0); return (bv - av) || a.title.localeCompare(b.title); }); const max = Math.max(1, ...rows.map(item => metric === 'likes' ? (stats[item.id]?.likesBy || []).length : metric === 'dislikes' ? (stats[item.id]?.dislikesBy || []).length : (stats[item.id]?.views || 0))); target.innerHTML = rows.map((item,index) => { const value = metric === 'likes' ? (stats[item.id]?.likesBy || []).length : metric === 'dislikes' ? (stats[item.id]?.dislikesBy || []).length : (stats[item.id]?.views || 0); return '<a class="chart-row" href="' + item.href + '"><span class="chart-rank">' + String(index + 1).padStart(2,'0') + '</span><img src="' + item.art + '" alt=""><span class="chart-song"><strong>' + escapeHtml(item.title) + '</strong><small>' + escapeHtml(item.artist) + (item.private ? ' · Private' : '') + '</small><i style="width:' + Math.max(8, Math.round(value / max * 100)) + '%"></i></span><span class="chart-value">' + value + '<small>' + metric + '</small></span></a>'; }).join(''); }); }); }
function bindAccountForm() { const form = document.getElementById('communityAuthForm'); const create = document.getElementById('communityCreate'); const signOutButton = document.getElementById('communitySignOut'); if (!form) return; const status = document.getElementById('communityAuthStatus'); form.addEventListener('submit', async event => { event.preventDefault(); try { const credentials = getCredentials(); status.textContent = 'Signing in…'; await login(credentials.username, credentials.pin, false); status.textContent = ''; } catch (error) { status.textContent = error.message === 'Account not found.' || error.message.includes('PIN') || error.message.includes('Username') ? error.message : 'Could not sign in. Check the username and PIN.'; } }); if (create) create.addEventListener('click', async () => { try { const credentials = getCredentials(); status.textContent = 'Creating account…'; await login(credentials.username, credentials.pin, true); status.textContent = ''; } catch (error) { status.textContent = error.message.includes('Username') || error.message.includes('PIN') ? error.message : 'That username may already be taken.'; } }); if (signOutButton) signOutButton.addEventListener('click', logout); }

async function start() { if (!firebaseConfigured) { setSetup('Demo mode is active. Add Firebase config to enable shared accounts and cross-device data.'); renderLocalAccount(); if (document.getElementById('listenerChart')) renderListenerRows(localListenerRows()); if (document.getElementById('profileName')) renderProfileLists(readLocal()); renderSongCommunity(new URLSearchParams(location.search).get('track') || '01'); return; } try { const app = initializeApp(config); db = getFirestore(app); root = doc(db, FIREBASE_ROOT, FIREBASE_ROOT_ID); accounts = collection(root, 'accounts'); bindAccountForm(); const session = readSession(); if (session) { const existing = await accountSnapshot(session.usernameKey); if (existing) currentUser = {...session, displayName:existing.displayName || existing.username}; else writeSession(null); } updateAccountUi(); const params = new URLSearchParams(location.search); const songId = params.get('track') || '01'; renderSongCommunity(songId); renderRemoteListeners(); renderRemoteSongCharts(); if (document.getElementById('profileName')) renderRemoteProfile(params.get('uid') || (currentUser && currentUser.usernameKey)); if (document.body.classList.contains('song-page') && (!document.body.classList.contains('private-song-locked') || sessionStorage.getItem('melation1020Unlocked') === 'yes')) recordView(songId); } catch (error) { setSetup('Firestore could not initialize. Check the Firebase project and Firestore rules.'); renderLocalAccount(); renderSongCommunity(new URLSearchParams(location.search).get('track') || '01'); } }

window.MelationCommunity = { isReady:() => true, isRemote:() => Boolean(db), user:() => currentUser, login, logout, react, recordView, recordPlay, recordListen, openAuthPrompt, formatDuration };
start();
