import { initializeApp, getApps } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js';
import { getFirestore, doc, getDoc, setDoc, collection } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js';
import { catalog } from './community-data.js';

const config=window.MELATION_FIREBASE_CONFIG||{};const ROOT='melationSound';const ROOT_ID='main';const SESSION_KEY='melationSoundAccount';let db=null;let accounts=null;let key='';let data=null;let pendingImage='';
function session(){try{return JSON.parse(sessionStorage.getItem(SESSION_KEY)||'null');}catch(error){return null;}}
function setStatus(value,error=false){const element=document.getElementById('profileEditStatus');if(element){element.textContent=value;element.style.color=error?'#ffadad':'';}}
function imageData(file){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),image=new Image();image.onload=()=>{URL.revokeObjectURL(url);const size=Math.min(700,image.naturalWidth,image.naturalHeight),canvas=document.createElement('canvas');canvas.width=size;canvas.height=size;canvas.getContext('2d').drawImage(image,0,0,size,size);resolve(canvas.toDataURL('image/jpeg',.82));};image.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('That image could not be read.'));};image.src=url;});}
async function start(){const owner=session();key=new URLSearchParams(location.search).get('uid')||owner?.usernameKey||'';if(!key||!owner||owner.usernameKey!==key)return;if(!config.apiKey||!config.projectId||!config.appId)return;try{const app=getApps().find(item=>item.name==='profileEditor')||initializeApp(config,'profileEditor');db=getFirestore(app);accounts=collection(db,ROOT,ROOT_ID,'accounts');const snapshot=await getDoc(doc(accounts,key));if(!snapshot.exists())return;data=snapshot.data();document.getElementById('profileEditPanel').hidden=false;document.getElementById('profileEditBio').value=data.profileBio||'';const select=document.getElementById('profileEditFavorite');select.innerHTML='<option value="">No favorite song</option>'+catalog.map(item=>'<option value="'+item.id+'">'+item.title+' · '+item.artist+'</option>').join('');select.value=data.favoriteSong||'';if(data.profileImage)document.getElementById('profileEditAvatar').src=data.profileImage;bind();}catch(error){setStatus('Profile editing is temporarily unavailable.',true);}}
function bind(){document.getElementById('profileEditImage').addEventListener('change',async event=>{const file=event.target.files?.[0];if(!file)return;try{pendingImage=await imageData(file);document.getElementById('profileEditAvatar').src=pendingImage;setStatus('Image ready. Click Save profile.');}catch(error){event.target.value='';setStatus(error.message,true);}});document.getElementById('profileEditSave').addEventListener('click',async()=>{const fields={profileBio:document.getElementById('profileEditBio').value.trim().slice(0,240),favoriteSong:document.getElementById('profileEditFavorite').value,updatedAtMs:Date.now()};if(pendingImage)fields.profileImage=pendingImage;try{await setDoc(doc(accounts,key),fields,{merge:true});pendingImage='';setStatus('Profile saved.');}catch(error){setStatus('Could not save your profile. Publish the current Firestore rules and try again.',true);}});}
start();
